### ISSUE TITLE
Human readable actor names

### ISSUE THREAD

**Issue by tommoor** [flippercloud/flipper#389] opened 2018-12-10 21:23 UTC
Right now in flipper our actor names look something like:

![image](https://user-images.githubusercontent.com/380914/49762461-ae96d700-fc7e-11e8-85c9-d2176e9c39dc.png)

It would be nice if there was a way to specify a human readable string, eg by using the `to_s` method on the model. Perhaps there is a way to do this and I'm missing it? If so apologies.

**Comment by jnunemaker** [comment] 2018-12-12 16:30
I totally love this idea. I was thinking that likely the easiest way would be some sort of hydrator for actors. Given a dehydrated actor id (or ids) it invokes a block you provide to return a fully hydrated object (AR model, or whatever). Something in Flipper::UI config like actor_hydrator could maybe do this. I'd probably make it work with batches of ids by default to avoid n+1 lookups too.

**Comment by jnunemaker** [comment] 2018-12-12 16:30
Another alternative would be to store this along with the actor id but becomes a cache invalidation issue pretty quick.

**Comment by DonSchado** [comment] 2020-05-13 05:55
I Would like to follow up on this. 
It would be very helpful to have some simple information next to the actor, 
because in a long list of `User:1234567` it get's out of hand which customer is allowed to see the feature very quickly.

So I guess either we could store this information in the Gate Table, or (preferable) have another flipper method in the model like `flipper_name` to be able to delegate that information to a custom column i.e. username, email...

**Comment by scottbarrow** [comment] 2020-07-03 21:02
could it be possible to maybe use an alternative unique attribute such as user.email?
e.g.
```def flipper_id
  email
```

**Comment by jnunemaker** [comment] 2020-07-04 00:13
You definitely can. The problem is that people change their email addresses so you’d need to be sure to update flipper if so.

**Comment by jnunemaker** [comment] 2022-08-15 16:54
Worth mentioning I laid out a plan for this if someone has the time to make a PR.

https://github.com/jnunemaker/flipper/issues/657#issuecomment-1215365903

**Comment by jevin** [comment] 2023-06-15 05:47
Hey @jnunemaker, I have PR #737 ready for this!

**Comment by jnunemaker** [comment] 2023-06-22 12:31
I’ll check it out soon! On vacation so I’ll be slower than usual. Thanks!

**Comment by jevin** [comment] 2023-07-10 04:44
> I’ll check it out soon! On vacation so I’ll be slower than usual. Thanks!

Hey John, hope you had a nice vacation! Let me know if you're able to get to this sometime soon.

**Comment by jevin** [comment] 2023-07-26 16:45
I realized I should have mentioned your handle. There goes @jnunemaker

**Comment by jnunemaker** [comment] 2023-11-04 17:55
closed by https://github.com/flippercloud/flipper/pull/737

**Closed by jnunemaker** 2023-11-04 17:55 UTC
